### ISSUE TITLE
API 요청을 위한 환경설정을 한다.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#11]
## 목적
- API를 사용할 수 있도록 환경 설정을 하고, 잘 연결되는지 테스트한다.

## Tasks
- [x] axios 인스턴스 설정
- [x] CORS 설정
- [x] axios로 CRUD 요청하는 메소드 모아놓는 클래스 생성
- [x] 간단하게 get으로 연결테스트 해보기
