### ISSUE TITLE
카드 create API에 요청을 보내 카드를 생성하는 기능을 구현한다.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#12]
## 목적
-  카드 에디터에서 create API를 통해 서버에 요청을 보내면 카드 생성이 성공적으로 이루어질 수 있도록 한다.

## Tasks
- [x] 프론트에서에서 formData를 이용해 데이터와 이미지를 POST하는 코드를 짠다.
- [x] 프론트에서의 요청이 성공적으로 이루어지도록 프론트와 서버에 발생하는 오류를 고친다.
- [x] 원하는 형식으로 데이터가 잘 저장이 되고 오류는 나지 않는지 테스트해본다.

**Comment by bluepebble25** [comment]
## 겪은 문제 1
### useState에서 파일을 빈 파일 객체로 초기화하는 법
이렇게 초기값이 할당된 useState에
```js
const [cardCustomFront, setCardCustomFront] = useState({
  type: 'color',
  value: colorPalette.white,
  fontColor: 'black',
});
```
기존에 없던 프로퍼티를 추가해서 새로 setState하니,
```js
setCardCustomFront({
  ...cardCustomFront,
  type: 'image',
  value: selectedFiles[0],
  file: files[0],
})
````
> 개체 리터럴은 알려진 속성만 지정할 수 있으며 'SetStateAction<{ type: string; value: string; fontColor: string; }>' 형식에 'file' 프로퍼티가 없습니다. (ts2345)

이런 현상이 발생했다.
그래서 이렇게
```js
const [cardCustomFront, setCardCustomFront] = useState({
  type: 'color',
  value: colorPalette.white,
  fontColor: 'black',
  file: null
});
```
`file: null`로 file 프로퍼티를 초기화해줬더니 새로 file을 setState하려고 하면 null에는 File을 할당할 수 없다고 한다.
new File()로 초기화해줘야 하는데 File 인스턴스는 어떻게 생성하는 걸까?

### 해결법
file 프로퍼티를 `new File([], 'file1')`로 초기화해준다.
new File(배열, 파일명)처럼 생성하면 되는데, 여기서 배열은 파일의 데이터를 담고 있는 배열이다.

**Comment by bluepebble25** [comment]
## 겪은 문제 2
### multer에서 한글로 된 파일명이 깨지는 현상
multer를 1.4.5 버전을 쓰고 있었다.
근데 한글로 된 파일명이 iso-8859-1 형태로 저장돼서 파일명이 깨져보이는 문제가 발생했다.

### 해결법
1.4.4 버전으로 다운그레이드 해준다. 1.4.4 버전으로 바꾸니 한글로 파일명이 잘 저장된다.
> npm uninstall multer

> npm install multer@1.4.4
