### ISSUE TITLE
앨범에서 카드를 클릭하면 카드 상세정보 페이지가 모달로 뜨게 라우팅 및 마크업을 한다.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#15]
## 목적
- Book의 카드를 클릭하면 URL 경로가 `/cards/:id` 형식으로 변하면서 카드 상세정보를 담은 모달창이 뜨게 한다.
- Book의 카드를 누르면 뒤의 배경 맥락은 그대로 유지하면서 새로 모달이 뜨게 하고, 만약 URL로 직접 접근한다면 Book을 보여주는 초기화면을 띄우고, 그 위에 모달창을 렌더링한다.

## Tasks
- [x] React-router-dom의 중첩라우팅과 Outlet을 이용해, 메인화면의 아래에 모달 역할을 할 카드 상세페이지를 위치시키고, `/cards/:id` path를 부여한다.
- [x] Book의 CardUI에 카드 상세페이지로 갈 수 있게 `<Link/>`를 연결한다.
- [x] 카드 상세페이지에  dimmed와 카드 컴포넌트, 버튼 컴포넌트를 배치하고 스타일링한다.
