### ISSUE TITLE
카드 상세페이지에서 카드 뒤집기 기능을 추가한다.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#17]
## 목적
- 카드 위에 띈 회전 아이콘을 클릭하면 카드가 뒤집히게 한다.

## Tasks
- [x] 카드 회전 아이콘을 `position: absolute`로 카드 컴포넌트 중앙에 위치시킨다.
- [x] 카드가 현재 앞면인지 뒷면인지 구분하기 위한 state를 만들고, 회전 아이콘에 onClick 이벤트를 붙여 토글되게 한다.
- [x] 카드 영역 위에 마우스가 들어오면 버튼이 보이고, 마우스가 나가면 버튼이 보이지 않게 한다.

**Comment by bluepebble25** [comment]
## 문제 해결 방법
### `position: absolute`로 지정한 요소를 정 중앙에 위치시키는 법
- absolute 요소의 상위 요소를 relative로 잘 감쌌다면, `left: 50%, top: 50%`을 줘서 가운데에 위치시킨다.
- absolute 요소의 위치 기준은 맨 위 왼쪽 꼭짓점이므로, 자기 몸체의 절반만큼을 왼쪽과 위로 이동시키기 위해
  `transform: translate(-50%, -50%)`을 준다.

### 카드 영역에 마우스가 위치할 때 버튼이 보이게 하기
- 마우스가 카드 위에 위치하는지 여부를 저장하는 state를 만든다.
- onMouseOver 이벤트는 마우스가 요소 위에 위치할 때 계속 발생하므로, 들어올 때와 나갈때를 감지하는 `onMouseEnter`와 `onMouseLeave` 이벤트를 Card 요소에 준다.
- `onMouseEnter`일 때는 카드 위에 마우스 위치하는지 여부를 setState를 이용해 true로, `onMouseLeave`에는 false로 설정한다.
- 버튼 요소에 state가 true이면 `display: block`, false면 `display: none`을 준다.
