### ISSUE TITLE
카드 에디터 화면을 벗어나려고 하면 경고해주는 기능을 추가하자.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#27]
## 목적
카드 에디터 화면에서 뒤로가기를 누르면 현재 저장사항을 모두 잃을 수 있는데 돌아가겠냐고 확인하는 Confirm 창을 띄운다.

## Tasks
- [x] 방법을 조사해서 정리한다.
- [x] 뒤로가기 방지
- [x] 창 닫기, 새로고침 방지
- [x] 페이지 이동 방지

**Comment by bluepebble25** [comment]
## 뒤로가기 방지, 창닫기/새로고침 방지 구현 방법
useEffect로 window에 뒤로가기 혹은 창닫기/새로고침을 감지하는 이벤트 리스너를 등록하는 방식으로 해결했다.

### 뒤로가기 방지
- 페이지가 렌더링되자마자 history.pushState로 빈 url 기록을 넣어놓는다. 그러면 뒤로가기를 눌러도 빈 히스토리가 pop 되면서 이전 페이지로 가는 것을 방지한다.
- pop 이벤트가 감지되어 preventGoBack 함수가 실행된다. pop으로 써버린 빈 히스토리를 다시 채워넣고, confirm 창을 띄운다.
- confirm 창에서 확인을 눌렀다면 이전 페이지로 navigate 시킨다.

### 창닫기/새로고침 방지
- `beforeunload` 이벤트리스너를 등록한다. before unload 라는 이름에서 알 수 있듯이 페이지가 unload(창을 닫거나 새로고침)되기 전에 발생하는 이벤트이다.
- beforeunload 이벤트를 통해 창을 닫거나 새로고침하는 것을 중간에 취소할 수 있다.
- `e.preventDefault()`로 unload를 취소하고
- 크롬에서 사용하려면 `e.returnValue = ''`를 추가로 작성해야 브라우저가 인식해서 confirm 창을 띄워준다.

```js
export const useBlock = (message: string) => {
  const navigate = useNavigate();

  const preventGoBack = useCallback(() => {
    window.history.pushState(null, '', window.location.href);
    const result = window.confirm(message);
    if (result) {
      navigate('/');
    }
  }, [message, navigate]);

  const preventClose = (e: BeforeUnloadEvent) => {
    e.preventDefault();
    e.returnValue = '';
  };

  useEffect(() => {
    window.history.pushState(null, '', window.location.href);
    window.addEventListener('popstate', preventGoBack);
    window.addEventListener('beforeunload', preventClose);

    return () => {
      window.removeEventListener('popstate', preventGoBack);
      window.removeEventListener('beforeunload', preventClose);
    };
  }, [preventGoBack]);
};
```

## 또 다른 문제점 (로고를 클릭해 메인 페이지로 이동하는 것 방지)
브라우저의 인터페이스를 통해 `뒤로가기`, `url 변경으로 이동`, `새로고침`, `창닫기`를 방지하는데 성공했는데 로고를 클릭하니 허무하게 바로 메인 페이지로 이동된다. 앞에서 등록한 이벤트들은 모두 브라우저 인터페이스로 조작한 것에만 해당되나보다.

그래서 다음과 같이 로고 클릭을 한 번 block할 필요가 있을 때 `shouldBlockPage` props를 true로 주면, Link 클릭 이벤트를 방지하고 confirm창으로 의사를 물어보도록 했다.
```js
<Logo margin="36px" shouldBlockPage={true} />
```
```js
// Logo component
const preventGoBack = (e: React.MouseEvent) => {
    if (shouldBlockPage) {
      e.preventDefault();
      const result = window.confirm(
        '뒤로가기를 하면 현재 작성하고 있는 사항을 모두 잃게 되는데 괜찮겠어요?'
      );
      if (result) {
        navigate('/');
      }
    }
  };
  return (
    <h1 css={headerStyle(margin)}>
      <Link to="/cards" onClick={preventGoBack}>
        <span css={logoStyle}>Phoca Review</span>
      </Link>
    </h1>
  );
```

## custom hook에서 반환값이 꼭 필수는 아니라는 걸 알게되다
페이지 내부에 위의 페이지 이동 방지 로직을 적으려니 너무 길어서 hook으로 분리했는데, 만들어놓고 보니 return 값이 없어서 당황했다. 그동안 내가 써오고 만들어왔던 hook은 return값이 있었는데 return 값이 없어도 괜찮나 하는 의문이 들었다.

답은 없어도 된다. 이다.
[React 공식 사이트 문서](https://ko.reactjs.org/docs/hooks-effect.html)에서 다음과 같이 hook에서 return값이 꼭 필수인 건 아니라고 말하고 있다.
> We don’t have to return a named function from the effect. We called it cleanup here to clarify its purpose, but you could return an arrow function or call it something different.

그래서 그냥 페이지 block이 필요한 곳에서 `useBlock`으로 사용하면 된다.

## useCallback()의 용도를 알게되다
- 그 전에는 함수를 dependencies 배열에 넣으면 무한 재귀호출을 하는 현상이 발생해서, 노란 줄로 경고가 뜸에도 불구하고 디펜던시 배열에 무한반복이 일어나게 하는 요소들을 넣지 않았다.
- 그런데 오늘 그 원인을 알았다. 컴포넌트가 state의 변경 등으로 재랜더링 될 때마다, 컴포넌트 내부에 선언한 함수들도 새로 생성되어서 새로운 address를 할당받는 게 원인이었다. 디펜던시 배열에 있는 함수가 새 address를 받았으니 디펜던시가 변경되었다고 생각하고 또 다시 렌더링되고, 그러면 또 address가 변경되어서 다시 렌더링되고...의 굴레였던 것이다.
- 그것을 방지하기 위해 함수에 진짜 변경사항이 없을 때는 새로 생성하지 않도록 함수를 메모리에 기억해놓는 함수가 바로 useCallback()이다.
