### ISSUE TITLE
카드 에디터 화면을 구현한다.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#4]
## 목적
> 카드 에디터 화면을 마크업하고 구성요소를 컴포넌트화한다.
> 카드 편집 미리보기의 핵심 기능을 붙인다.

## Tasks
- [x] 화면 구성요소를 컴포넌트화한다. 버튼 등의 컴포넌트들은 props에 따라 재사용할 수 있도록 만든다.
- [x] 카드 뒤집기 기능을 만든다.
- [x] 입력한 카드 정보가 미리보기에 반영되게 한다.
- [x] 선택한 카드 배경색상 및 텍스트 색상이 화면에 반영되게 한다.
