### ISSUE TITLE
카드 편집 기능을 구현한다.

### ISSUE THREAD

**Issue by bluepebble25** [bluepebble25/phoca-review#5]
## 목적
> 카드 편집 기능의 세부 기능을 구현한다. 

## Tasks
- [x] Color picker로 카드 배경색을 선택할 수 있는 기능을 구현한다.
- [x] 카드 배경 이미지 업로드 및 미리보기 기능을 구현한다.
- [x] '내용' 항목 입력 시 글자 수 세기 및 글자 수 제한 기능을 구현한다.
